//PepperText.js this is such a stupid way to do this - need back end
export const ptext = [
	"Think outside the box.",
	"S Y N E R G Y",
	"Bandwidth!!!",
	"Circle Back.",
	"At a high level...",
	"Table this conversation\nuntil Thursday",
	"Run it up the flagpole -",
	"Moving the needle...",
	"Pow wow",
	"Win-win situation",
	"It is what it is -",
	"Content is king.",
	"Thanks in advance;",
	"Ducks in a row:",
	"Disrupt, Disrupt, Disrupt",
	"A GAME CHANGER",
	"Back to the drawing board...",
	"Par for the course.",
	"apples to apples",
	"Bite the bullet",
	"With all due respect....\n.......",
	"The elephant in the room.",
	"Making the world a better place!",
	"At the end of the day...",
	"Relevant information:",
	"It's a no brainer!",
	"we ran the numbers",
	"Hit the ground running!",
	"Best Practice",
	"Selling points",
	"Do more with LESS",
	"alignment and activity",
	"L E V E R A G E",
	"Mind share",
	"R.O.B.U.S.T.",
	"Investing in ourSELVES",
	"e n t e r p r i s e",
	"Water under the bridge.",
	"Drrrriving Innovation",
	"Raising morale:",
	"Digital PROductivity",
	"A G I L E",
	"Back to reality!",
	"Siloed thinking",
	"Going forward...",
	"Giving 110%",
	"ALL HANDS ON DECK",
	"Adding Value",
	"Ramp up up up",
	"For the business side..."
]
