//PepperText.js this is such a stupid way to do this - need back end
export const ptext = [
	"Think outside the box.",
	"S Y N E R G Y",
	"Bandwidth!!!",
	"Circle Back.",
	"At a high level...",
	"Table this conversation\nuntil Thursday",
	"Run it up the flagpole -",
	"Moving the needle...",
	"Pow wow",
	"No.",
	"22,000",
	"Win-win situation",
	"It is what it is -",
	"Content is king.",
	"Thanks in advance;",
	"Ducks in a row:",
	"Answer the following: ",
	"But let me backtrack.",
	"That reminds me...",
	"Disrupt, Disrupt, Disrupt",
	"A GAME CHANGER",
	"Picture this.",
	"We'll Be\nRight Back",
	"This is not good.",
	"Over 30%",
	"Back to the drawing board...",
	"Par for the course.",
	"comparing apples\nto apples",
	"32 minutes",
	"(Audience Participation)",
	"Bite the bullet",
	"12 seconds",
	"Take note of this figure.",
	"With all due respect....\n.......",
	"The elephant in the room.",
	"Making the world a better place!",
	"At the end of the day...",
	"Relevant information:",
	"*Correction: ", 
	"<Wait For Applause>",
	"You may ask, \"WHY?\"",
	"It's a no brainer!",
	"At least 750,000",
	"we ran the numbers",
	"Hit the ground running!",
	"Yes.",
	"Last meeting's minutes...",
	"A question for the audience: ",
	"With that in mind,\nour next step is",
	"In a perfect world -- ",
	"Best Practice",
	"Our product will feature: ",
	"What we should be doing better:",
	"In the last year",
	"GIVE FEEDBACK",
	"Observe!",
	"Here is the market breakdown.",
	"Selling points",
	"Do more with LESS",
	"alignment and activity",
	"L E V E R A G E",
	"First of all:",
	"Look to your left,\nand look to your right.",
	"PAUSE. THINK.",
	"Nearing 1 million",
	"As of last year,",
	"Mind share",
	"You may not be aware - ",
	"An introduction is in order:",
	"R.O.B.U.S.T.",
	"Consider the following: ",
	"Investing in ourSELVES",
	"(BRIEF INTERMISSION)",
	"e n t e r p r i s e",
	"9",
	"I want to hear some ideas.",
	"Water under the bridge.",
	"Drrrriving Innovation",
	"Raising morale:",
	"Before I continue - ",
	"*IMPORTANT*",
	"What are your thoughts?",
	"But is it scalable?",
	"Digital PROductivity",
	"A G I L E",
	"We have been underperforming.",
	"Back to reality!",
	"Siloed thinking",
	"But first, a story - ",
	"Going forward...",
	"Giving 110%",
	"3.89 on average",
	"Is this SMART?",
	"Let's start over.",
	"ALL HANDS ON DECK",
	"Adding Value",
	"Be engaging",
	"Ramp up up up",
	"For the business side..."
]
