//PepperText.js this is such a stupid way to do this - need back end
export const ptext = [
	"Think outside the box.",
	"Synergy",
	"Bandwidth",
	"Circle back",
	"At a high level...",
	"Table this conversation",
	"Run it up the flagpole",
	"Moving the needle",
	"Pow wow",
	"Win-win",
	"It is what it is -",
	"Content is king",
	"Thanks in advance",
	"Ducks in a row",
	"Disrupt",
	"Game changer",
	"Back to the drawing board...",
	"Par for the course",
	"Apples to apples",
	"Bite the bullet",
	"With all due respect -",
	"The elephant in the room",
	"Making the world a better place:",
	"At the end of the day",
	"Relevant information",
	"It's a no brainer - ",
	"We ran the numbers",
	"Hit the ground running!",
	"Best practice",
	"Selling points",
	"Do more with less",
	"Alignment",
	"Leverage",
	"Mind share",
	"Robust",
	"Investing in ourselves",
	"Enterprise",
	"Water under the bridge",
	"Driving innovation",
	"Raising morale:",
	"Digital productivity",
	"Agile",
	"Back to reality",
	"Siloed thinking",
	"Going forward",
	"Giving 110%",
	"All hands on deck",
	"Adding value",
	"Ramp up",
	"The business side..."
]
